CREATE TABLE USUARIO_AUTORIZACAO_AUDITORIA (
	ID BIGINT,
	ID_USUARIO int,
	ID_PERMISSAO int ,
	ID_PREVILEGIO int,
    USUARIO_CRIACAO  VARCHAR(250),
    USUARIO_ALTERACAO VARCHAR(250),
    DATA_CRIACAO TIMESTAMP,
    DATA_ALTERACAO TIMESTAMP,
    REV BIGINT NOT NULL,
    REVTYPE BIGINT
);