CREATE TABLE PERMISSAO_AUDITORIA  (
	ID BIGINT,
	NOME VARCHAR ( 150 )  NULL,
	USUARIO_CRIACAO VARCHAR(250),
    USUARIO_ALTERACAO VARCHAR(250),
    DATA_CRIACAO TIMESTAMP,
    DATA_ALTERACAO TIMESTAMP,
    REV BIGINT NOT NULL,
    REVTYPE BIGINT
);